// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIAxf9rg5OKzKbsLyqX9r8DPKN6Sw1RQ',
    appId: '1:318880877839:web:404b075cc107aa4725827a',
    messagingSenderId: '318880877839',
    projectId: 'library-management-a21eb',
    authDomain: 'library-management-a21eb.firebaseapp.com',
    storageBucket: 'library-management-a21eb.firebasestorage.app',
    measurementId: 'G-GXV1LDMHTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKOwiQ1jPztZD-suDa6u3WGTZ2X--aXP8',
    appId: '1:318880877839:android:51e0bc890c22d05225827a',
    messagingSenderId: '318880877839',
    projectId: 'library-management-a21eb',
    storageBucket: 'library-management-a21eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4KzJfrHW7jb1QCG6qEpK2dnjIMOHOJYk',
    appId: '1:318880877839:ios:89b4e8d0de2d2ecd25827a',
    messagingSenderId: '318880877839',
    projectId: 'library-management-a21eb',
    storageBucket: 'library-management-a21eb.firebasestorage.app',
    iosClientId: '318880877839-j3kldo1j9e3af96t2n14n6kkggfpdbos.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4KzJfrHW7jb1QCG6qEpK2dnjIMOHOJYk',
    appId: '1:318880877839:ios:89b4e8d0de2d2ecd25827a',
    messagingSenderId: '318880877839',
    projectId: 'library-management-a21eb',
    storageBucket: 'library-management-a21eb.firebasestorage.app',
    iosClientId: '318880877839-j3kldo1j9e3af96t2n14n6kkggfpdbos.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOIAxf9rg5OKzKbsLyqX9r8DPKN6Sw1RQ',
    appId: '1:318880877839:web:fb479f027d0f3cac25827a',
    messagingSenderId: '318880877839',
    projectId: 'library-management-a21eb',
    authDomain: 'library-management-a21eb.firebaseapp.com',
    storageBucket: 'library-management-a21eb.firebasestorage.app',
    measurementId: 'G-1G0CFMHGZ8',
  );
}
